### ISSUE TITLE
为什么前几天更新了版本之后就用不了了

### ISSUE THREAD

**Issue by z598523287** [wozaiha/NamaryaButterflyHud#12]
hudinjector打开CMD也是闪一下就没了
用start打开甚至会提示Python 3.11 64-bit not found, please install it or add it to your PATH.
明明之前都能用,隔壁DPS统计也没问题

**Comment by wozaiha** [comment]
请详细描述遇到的问题
还有请运行start.cmd

Mikazuki ***@***.***>于2024年3月24日 周日19:24写道：

**Comment by z598523287** [comment]
刚才敲了回车直接给我标题就发出去了,内容已经编辑了

**Comment by wozaiha** [comment]
截个图看看？
运行start.cmd

**Comment by z598523287** [comment]
![BI%~P95OUA}I2MMNICHZR}S](https://github.com/wozaiha/NamaryaButterflyHud/assets/22060478/e00ee761-2fd5-4f7b-b755-3e859e9417b5)

**Comment by z598523287** [comment]
python我肯定都装好了的,DPS统计和之前这个蝴蝶版本我都能用

**Comment by wozaiha** [comment]
win+r运行cmd
输入python 回车
显示什么？

**Comment by z598523287** [comment]
会给我跳出 Microsoft Store

**Comment by wozaiha** [comment]
AppData\Local\Programs\Python\Python311 文件夹夹夹存在么？

**Comment by z598523287** [comment]
![image](https://github.com/wozaiha/NamaryaButterflyHud/assets/22060478/e8e9a899-68c3-414f-ac1e-1138c30dc752)
有的

**Comment by wozaiha** [comment]
添加一下path看看

https://cloud.tencent.com/developer/article/1855492

**Comment by z598523287** [comment]
ok好了,之前就加了一个Scripts的文件夹进环境变量
