### ISSUE TITLE
基址是怎么找的呢

### ISSUE THREAD

**Issue by mobclix** [wozaiha/NamaryaButterflyHud#14]
想再搞个飞哥的玩玩，这基址从哪过来的呢。python水平有限，实在读不懂了。。

![image](https://github.com/wozaiha/NamaryaButterflyHud/assets/40229583/966a80a9-6359-4f7f-809f-9511695de176)

**Comment by wozaiha** [comment]
ce+知道自己在找什么+运气

**Comment by mobclix** [comment]
> ce+知道自己在找什么+运气

我想知道的是a1这个参数从哪传进来的。。

**Comment by mobclix** [comment]
> ce+知道自己在找什么+运气

我再研究研究

**Comment by wozaiha** [comment]
我没去深究，只是显示而已又不是改蝴蝶数量，估计应该是object管理器，你dbg断一下就能抓到

**Comment by mobclix** [comment]
> 我没去深究，只是显示而已又不是改蝴蝶数量，估计应该是object管理器，你dbg断一下就能抓到

请教一下，我找到了飞哥just+1的地址，但是在218C3F0处注入会破环一些原指令，通过hook.original()返回执行的时候直接回到218C3FA处开始执行，而且寄存器内的值也改变了，导致后面报错。所以应该怎么选择注入地址呢？

![PixPin_2024-04-08_10-53-33](https://github.com/wozaiha/NamaryaButterflyHud/assets/40229583/4fa2b5b7-a216-4662-bd7c-0e08a3e0b98c)

![PixPin_2024-04-08_11-02-35](https://github.com/wozaiha/NamaryaButterflyHud/assets/40229583/b67c7913-f3ff-4711-a235-590f49f278f2)
