### ISSUE TITLE
运行injector后cmd窗口闪现消失，游戏内未看到相关功能

### ISSUE THREAD

**Issue by Swernan** [wozaiha/NamaryaButterflyHud#4]
环境
--
win11
python3.11.6
安装过act和gbfr logs

问题描述
--
运行injector后cmd窗口闪现消失，游戏内未看到相关功能
一瞬间的cmd窗口为全黑

**Comment by wozaiha** [comment]
act是否可以运行？

**Comment by Swernan** [comment]
可以，logs和parser也可以运行

**Comment by wozaiha** [comment]
试一下用新增的cmd文件启动
